
export const SET_USER_CHOICE = "SET_USER_CHOICE";
export const SET_USER_COINS = "SET_USER_COINS";
export const INCREMENT_CURRENT_BET = "INCREMENT_CURRENT_BET";
export const DECREMENT_CURRENT_BET = "DECREMENT_CURRENT_BET";
export const SET_RANDOM_ANSWERS = "SET_RANDOM_ANSWERS";
// export const SET_SCORE = "SET_SCORE";



